name: Periodic health check

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployed app health
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-wuoz.onrender.com
          follow-redirect: true
          max-attempts: 3
          retry-delay: 15s
