name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello, show date and list files in the workflow directory
        run: |
          echo "Hello World!"
          date
          ls -l