name: Testing stuff

on:
  push:
    branches:
      - test-branch

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages contains '#skip'
        env:
          COMMIT_MESSAGES: ${{ contains(join(toJson(github.event.commits.*.message), ' '), '#skip') }}
        run: echo "$COMMIT_MESSAGES"
      -  run: echo ${{ secrets.DISCORD_WEBHOOK_URL }}